version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    container_name: simple_fastapi
    depends_on:
      - db
    command: ["gunicorn", "app.main:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
#    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pg_db
    ports:
      - "1000:5432"
    environment:
      - POSTGRES_HOST=$HOST
      - POSTGRES_DB=$DBMS
      - POSTGRES_USER=$USER_NAME
      - POSTGRES_PASSWORD=$PASSWORD
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
