"""Add datetime consumer_ticket_link

Revision ID: 0664384c556b
Revises: 376069b5274a
Create Date: 2024-07-09 18:09:26.260988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0664384c556b'
down_revision: Union[str, None] = '376069b5274a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_ticket_link', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('consumer_ticket_link', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
