"""initial_migration

Revision ID: a29dcc349914
Revises: 
Create Date: 2024-07-12 12:47:35.892229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


import fastapi_users_db_sqlalchemy.generics
import sqlalchemy_utils.types.email
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a29dcc349914'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.Enum('PERCENTAGE', 'AMOUNT', name='discounttypeenum').create(op.get_bind())
    op.sync_enum_values('public', 'discounttypeenum', ['PERCENTAGE', 'AMOUNT'],
                        [TableReference(table_schema='public', table_name='discounttypeenum', column_name='discount_type')])
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_table('consumer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_consumer_id'), 'consumer', ['id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discount_name', sa.String(), nullable=False),
    sa.Column('discount_type', postgresql.ENUM('PERCENTAGE', 'AMOUNT', name='discounttypeenum', create_type=False), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_tickets', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_name')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', postgresql.ENUM('PERCENTAGE', 'AMOUNT', name='discounttypeenum', create_type=False), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_promo_code_id'), 'promo_code', ['id'], unique=False)
    op.create_table('ticket_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', postgresql.ENUM('PREMIUM', 'PREMIUM1', 'PREMIUM2', 'BUSINESS', 'BUSINESS1', 'BUSINESS2', 'VIP', 'VIP1', 'VIP2', 'STANDARD', 'STANDARD1', 'STANDARD2', name='ticketcategoryenum', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_ticket_category_id'), 'ticket_category', ['id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('event_discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('is_cumulative', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'discount_id', name='uq_event_discount')
    )
    op.create_table('event_promo_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('is_cumulative', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'promo_code_id', name='uq_event_promo_code')
    )
    op.create_table('event_ticket_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_category.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'category_id', name='uq_event_category')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(), nullable=True),
    sa.Column('seat', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_category.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_table('consumer_ticket_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_status', postgresql.ENUM('PURCHASED', 'RESERVE', name='ticketstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', name='uq_ticket_id')
    )
    op.create_table('event_ticket_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('user_name', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
                    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
                              nullable=True),
                    sa.Column('role',
                              postgresql.ENUM('ADMIN', 'MODERATOR', 'VIEWER', name='userrole', create_type=False),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('phone_number'),
                    sa.UniqueConstraint('user_name')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # sa.Enum('ADMIN', 'MODERATOR', 'VIEWER', name='"UserRole"').drop(op.get_bind())
    # sa.Enum('ADMIN', 'MODERATOR', 'VIEWER', name='userrole').drop(op.get_bind())
    op.sync_enum_values('public', 'userrole', ['ADMIN', 'MODERATOR', 'VIEWER'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'discounttypeenum', ['PERCENTAGE', 'AMOUNT'],
                        [TableReference(table_schema='public', table_name='discounttypeenum',
                                        column_name='discount_type')])
    op.sync_enum_values('public', 'userrole', ['admin', 'moderator', 'viewer'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')])
    #
    # sa.Enum('ADMIN', 'MODERATOR', 'VIEWER', name='userrole').create(op.get_bind())
    # sa.Enum('ADMIN', 'MODERATOR', 'VIEWER', name='"UserRole"').create(op.get_bind())
    op.drop_table('event_ticket_link')
    op.drop_table('consumer_ticket_link')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_table('event_ticket_category')
    op.drop_table('event_promo_code')
    op.drop_table('event_discount')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_ticket_category_id'), table_name='ticket_category')
    op.drop_table('ticket_category')
    op.drop_index(op.f('ix_promo_code_id'), table_name='promo_code')
    op.drop_table('promo_code')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_consumer_id'), table_name='consumer')
    op.drop_table('consumer')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    # sa.Enum('PERCENTAGE', 'AMOUNT', name='discounttypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
